# Generated by Django 5.2.6 on 2025-09-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('income_increase', models.IntegerField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upgrade',
                'verbose_name_plural': 'Upgrades',
                'db_table': 'upgrade',
            },
        ),
        migrations.CreateModel(
            name='UserUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by',
                                              to='upgrades.upgrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_upgrades',
                                           to='users.tguser')),
            ],
            options={
                'verbose_name': 'User Upgrade',
                'verbose_name_plural': 'User Upgrades',
                'db_table': 'user_upgrade',
                'unique_together': {('user', 'upgrade')},
            },
        ),
    ]
