# Generated by Django 5.2.6 on 2025-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='photo',
            field=models.ImageField(null=True, upload_to='upgrades/'),
        ),
    ]
