# Generated by Django 5.2.6 on 2025-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
