# Generated by Django 5.2.6 on 2025-09-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskcompletion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(null=True, upload_to='tasks/'),
        ),
    ]
