# Generated by Django 5.2.6 on 2025-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
